/*
 * data.h
 *
 *  Created on: Jul 28, 2022
 *      Author: 79110
 */

#ifndef INC_DATA_H_
#define INC_DATA_H_

#include "stdint.h"

#define DATA_ADR_SIZE  10U

typedef enum {
  DATA_OK,
  DATA_ERROR_ADR
} DATA_ERROR;

typedef enum
{
  DATA_ADR_UNIQUE,
  DATA_ADR_CURRENT_0,
  DATA_ADR_CURRENT_1,
  DATA_ADR_CURRENT_2,
  DATA_ADR_CURRENT_3,
  DATA_ADR_CURRENT_4,
  DATA_ADR_CURRENT_5,
  DATA_ADR_CURRENT_6,
  DATA_ADR_CURRENT_7,
  DATA_ADR_CURRENT_8,
  DATA_ADR_CURRENT_9,
  DATA_ADR_CURRENT_10,
  DATA_ADR_CURRENT_11,
  DATA_ADR_CURRENT_12,
  DATA_ADR_CURRENT_13,
  DATA_ADR_CURRENT_14,
  DATA_ADR_CURRENT_15,
  DATA_ADR_CURRENT_16,
  DATA_ADR_CURRENT_17,
  DATA_ADR_CURRENT_18,
  DATA_ADR_CURRENT_19,
  DATA_ADR_CURRENT_20,
  DATA_ADR_VOLTAGE_BAT,
  DATA_ADR_VOLTAGE_0,
  DATA_ADR_VOLTAGE_1,
  DATA_ADR_VOLTAGE_2,
  DATA_ADR_VOLTAGE_3,
  DATA_ADR_DIN,
  DATA_ADR_DOUT,
  DATA_ADR_STATUS,
  DATA_ADR_LUA
} DATA_ADR;

DATA_ERROR eDATAget ( DATA_ADR adr, uint8_t* out, uint8_t* length );

#endif /* INC_DATA_H_ */
